import Head from 'next/head'
import { PaymentForm } from '../components'
import ConvertToPdf from '../components/ConvertToPdf'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
          <PaymentForm />
      </div>

      
    </div>
  )
}
